spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: ${ctrip_appid}
  
server:
  port: ${server_port}
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log
