spring:
  application:
    name: ${spring_application_name}
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: ${ctrip_appid}
  
server:
  port: ${server_port}
  
logging:
  file: D:/opt/logs/100003171/apollo-configservice.log
