spring:
  application:
    name: apollo-portal
  profiles:
    active: github  #激活application-github.properties属性文件
  resources:
    cache-period: 3600
  datasource:
    url: ${spring.datasource.url}
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}

server:
  port: 8070

logging:
  file: /opt/logs/100003173/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP


